services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    environment:
      APP_ENV: prod
    depends_on:
      - db
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mariadb:latest
    container_name: btc_vault_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-btc_vault}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
