services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    environment:
      APP_ENV: dev
    depends_on:
      - db
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "10324:80"
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mariadb:latest
    container_name: btc_vault_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
      - database_data:/var/lib/mysql:rw
    ports:
      - "3310:3306"
    networks:
      - symfony

volumes:
  symfony_app_var:
  symfony_app_vendor:
  database_data:

networks:
  symfony:
    driver: bridge
